---
name: CD

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-cargo:
    name: Publishing to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --token "${{ secrets.CARGO_API_KEY }}"
